import React, { ReactNode } from "react";
import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css';
import '../scripts/index.js'
interface Props {
    children?: ReactNode
    title?: ReactNode
}
export default function Layout({ children, title }: Props) {
    return (
        <div>
            <Head>
                <title>{title ? `Next Amazona / ${title}` : 'Next Amazona '}</title>
                <meta name="description" content="Generated by create next app" />
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                {children}
            </main>

            <footer>
            </footer>
        </div>
    )
}
