import React, { ReactNode } from "react";
import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css';
import '../scripts/index'
interface Props {
    children?: ReactNode
    title?: ReactNode
}
export default function Layout({ children, title }: Props) {
    return (
        <div>
            <Head>
                <title>{title ? `Next Amazona / ${title}` : 'Next Amazona '}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className='cursor'></div>
                {children}
            </main>

            <footer>
            </footer>
        </div>
    )
}
